name: Publish patchwing_ci

on:
  push:
    tags:
      - "patchwing_ci-v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    uses: ./.github/workflows/publish_dart_package.yaml
    with:
      working_directory: packages/patchwing_ci
      tag_prefix: patchwing_ci-v
    permissions:
      id-token: write
