name: Publish patchwing_redis_client

on:
  push:
    tags:
      - "patchwing_redis_client-v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    uses: ./.github/workflows/publish_dart_package.yaml
    with:
      working_directory: packages/redis_client
      tag_prefix: patchwing_redis_client-v
      needs_redis: true
    permissions:
      id-token: write
